import React, { useState, useEffect } from 'react';
import { Course, TimeSlot, Booking } from '../types';
import { CITIES } from '../constants';
import { StorageService } from '../services/storageService';
import { Check, Calendar, Clock, MapPin, Phone, User, MessageSquare, ArrowLeft, Mail, DollarSign, Car, Loader2, BookOpen, Users, Info } from 'lucide-react';

export const BookingWizard: React.FC = () => {
  const [step, setStep] = useState<number>(1);
  const [loading, setLoading] = useState<boolean>(false);
  const [courses, setCourses] = useState<Course[]>([]);
  const [selectedCourse, setSelectedCourse] = useState<Course | null>(null);
  const [selectedDate, setSelectedDate] = useState<string>('');
  const [selectedSlot, setSelectedSlot] = useState<TimeSlot | null>(null);
  const [formData, setFormData] = useState({
    invitingUnit: '',
    contactName: '',
    contactPhone: '',
    contactSocial: '',
    contactEmail: '',
    city: '',
    notes: '',
    hourlyRate: '',
    hasTravelFee: 'yes'
  });
  const [slotAvailability, setSlotAvailability] = useState<{ [key in TimeSlot]: boolean }>({
    [TimeSlot.MORNING]: true,
    [TimeSlot.AFTERNOON]: true
  });

  // Load courses on mount
  useEffect(() => {
    const loadCourses = async () => {
        setLoading(true);
        const data = await StorageService.getAllCourses();
        setCourses(data);
        setLoading(false);
    };
    loadCourses();
  }, []);

  // Check availability when date changes
  useEffect(() => {
    const checkSlots = async () => {
        if (selectedDate) {
          setLoading(true);
          const isMorningFree = await StorageService.checkAvailability(selectedDate, TimeSlot.MORNING);
          const isAfternoonFree = await StorageService.checkAvailability(selectedDate, TimeSlot.AFTERNOON);
          setSlotAvailability({
            [TimeSlot.MORNING]: isMorningFree,
            [TimeSlot.AFTERNOON]: isAfternoonFree
          });
          setLoading(false);
        }
    };
    checkSlots();
  }, [selectedDate]);

  // Reset to step 1
  const handleReset = () => {
    setStep(1);
    setSelectedCourse(null);
    setSelectedDate('');
    setSelectedSlot(null);
    setFormData({
      invitingUnit: '',
      contactName: '',
      contactPhone: '',
      contactSocial: '',
      contactEmail: '',
      city: '',
      notes: '',
      hourlyRate: '',
      hasTravelFee: 'yes'
    });
  };

  const handleCourseSelect = (course: Course) => {
    setSelectedCourse(course);
    setStep(2);
  };

  const handleTimeSelect = (slot: TimeSlot) => {
    if (slotAvailability[slot]) {
      setSelectedSlot(slot);
      setStep(3);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedCourse || !selectedDate || !selectedSlot) return;

    setLoading(true);

    const newBooking: Booking = {
      id: '', // Will be generated by Firestore or ignored
      courseId: selectedCourse.id,
      courseName: selectedCourse.title,
      date: selectedDate,
      timeSlot: selectedSlot,
      invitingUnit: formData.invitingUnit,
      contactName: formData.contactName,
      contactPhone: formData.contactPhone,
      contactSocial: formData.contactSocial,
      contactEmail: formData.contactEmail,
      city: formData.city,
      notes: formData.notes,
      source: '網站預約',
      createdAt: Date.now(),
      hourlyRate: formData.hourlyRate ? parseInt(formData.hourlyRate) : 0,
      hasTravelFee: formData.hasTravelFee === 'yes'
    };

    await StorageService.addBooking(newBooking);
    setLoading(false);
    setStep(4);
  };

  // Loading Overlay
  const LoadingOverlay = () => (
    loading ? (
        <div className="absolute inset-0 bg-white/60 z-50 flex items-center justify-center backdrop-blur-sm rounded-xl">
            <div className="flex flex-col items-center gap-2">
                <Loader2 className="animate-spin text-blue-600" size={32} />
                <span className="text-sm font-medium text-slate-600">處理中...</span>
            </div>
        </div>
    ) : null
  );

  // Welcome Box Component
  const WelcomeBox = () => (
    <div className="max-w-5xl mx-auto mb-12 bg-white rounded-2xl p-8 border border-slate-100 shadow-md relative overflow-hidden flex flex-col md:flex-row items-center gap-8">
      {/* Decorative gradient bar */}
      <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-blue-500 to-indigo-600"></div>
      
      {/* Image Section - Left Side */}
      <div className="shrink-0 relative">
        <div className="https://hsuliang.github.io/booking/images/Aling-home.png">
            {/* 這裡請替換成您去背好的照片連結，目前使用示意圖 */}
            <img 
              src="https://hsuliang.github.io/booking/images/Aliang.png" 
              alt="丫亮笑長" 
              className="w-full h-full object-contain drop-shadow-xl"
            />
        </div>
        {/* Decorative circle behind */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-40 h-40 md:w-56 md:h-56 bg-blue-100 rounded-full -z-0 blur-sm"></div>
      </div>

      {/* Text Section - Right Side */}
      <div className="text-center md:text-left flex-grow space-y-4">
          <h1 className="text-3xl md:text-4xl font-bold text-slate-800 flex items-center justify-center md:justify-start gap-2">
             歡迎使用丫亮笑長的上課助手
          </h1>
          <p className="text-slate-600 text-lg leading-relaxed">
            這是一個專為課程邀約設計的快速預約平台。<br className="hidden md:block"/>
            您可以直接查詢我的行程空檔，選擇適合的課程並完成申請。<br/>
            系統將自動引導您完成所有步驟，讓我們開始吧！
          </p>
          
          <div className="pt-2 flex flex-wrap justify-center md:justify-start gap-3 text-sm text-slate-500">
            <span className="flex items-center gap-1 bg-slate-50 px-3 py-1.5 rounded-full border border-slate-200">
              <Check size={16} className="text-green-500"/> 線上即時查詢
            </span>
            <span className="flex items-center gap-1 bg-slate-50 px-3 py-1.5 rounded-full border border-slate-200">
              <Check size={16} className="text-green-500"/> 自動通知信件
            </span>
            <span className="flex items-center gap-1 bg-slate-50 px-3 py-1.5 rounded-full border border-slate-200">
              <Check size={16} className="text-green-500"/> 專人後續追蹤
            </span>
          </div>
      </div>
    </div>
  );

  // Step Indicators with Labels
  const StepIndicator = () => (
    <div className="flex items-center justify-center mb-12 px-4 relative">
      {[
          { num: 1, label: '選擇課程' },
          { num: 2, label: '查詢時段' },
          { num: 3, label: '填寫資料' }
        ].map((s) => (
        <div key={s.num} className="flex items-center relative">
          <div className="flex flex-col items-center relative z-10">
            <div className={`
                flex items-center justify-center w-12 h-12 rounded-full font-bold border-2 text-lg shadow-sm
                ${step === s.num ? 'bg-blue-600 text-white border-blue-600 scale-110' : 
                step > s.num ? 'bg-green-500 text-white border-green-500' : 
                'bg-white text-gray-400 border-gray-200'}
                transition-all duration-300
            `}>
                {step > s.num ? <Check size={24} /> : s.num}
            </div>
            <span className={`absolute -bottom-8 w-24 text-center text-sm font-medium ${step >= s.num ? 'text-slate-800' : 'text-slate-400'}`}>
                {s.label}
            </span>
          </div>
          
          {s.num < 3 && (
            <div className={`w-16 sm:w-32 h-1 mx-2 rounded-full ${step > s.num ? 'bg-green-500' : 'bg-gray-200'}`} />
          )}
        </div>
      ))}
    </div>
  );

  // Step 1: Select Course (Grid Card View)
  const renderStep1 = () => (
    <div className="relative min-h-[400px]">
      <LoadingOverlay />
      <div className="text-center mb-8">
        <h2 className="text-2xl font-bold text-slate-800 mb-2">課程一覽表</h2>
        <p className="text-slate-500">選擇課程並預約</p>
      </div>
      
      {courses.length === 0 && !loading ? (
         <div className="p-16 text-center text-slate-400 bg-slate-100 rounded-xl border border-dashed border-slate-300">
            <Info size={48} className="mx-auto mb-4 opacity-50"/>
            <p>目前沒有可預約的課程，請稍後再試。</p>
         </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {courses.map((course) => (
                <div key={course.id} className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden flex flex-col hover:shadow-lg transition-all duration-300 group">
                    <div className="h-48 bg-slate-200 relative overflow-hidden">
                        {course.imageUrl ? (
                            <img src={course.imageUrl} alt={course.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                        ) : (
                            <div className="flex items-center justify-center h-full text-slate-400">
                                <BookOpen size={48} />
                            </div>
                        )}
                        <div className="absolute top-2 right-2 bg-white/95 backdrop-blur-sm px-3 py-1 rounded-lg text-xs font-bold text-slate-800 shadow-sm border border-slate-100">
                            {course.category}
                        </div>
                    </div>
                    <div className="p-5 flex-grow flex flex-col">
                        <h3 className="font-bold text-xl text-slate-900 mb-2 group-hover:text-blue-600 transition-colors">{course.title}</h3>
                        <div className="text-xs text-slate-500 mb-4 flex flex-wrap items-center gap-2">
                            <span className="bg-slate-100 px-2 py-1 rounded flex items-center gap-1">
                                <Clock size={14} className="text-slate-400"/> {course.duration}
                            </span>
                            {course.targetAudience && (
                                <span className="bg-blue-50 text-blue-700 px-2 py-1 rounded flex items-center gap-1 max-w-full truncate">
                                    <Users size={14} /> {course.targetAudience}
                                </span>
                            )}
                        </div>
                        <p className="text-sm text-slate-600 line-clamp-3 mb-4 flex-grow">{course.description}</p>
                        
                        <button
                            onClick={() => handleCourseSelect(course)}
                            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded-lg transition-colors flex items-center justify-center gap-2 shadow-md hover:shadow-lg transform active:scale-[0.98]"
                        >
                            立即預約
                        </button>
                    </div>
                </div>
            ))}
        </div>
      )}
    </div>
  );

  // Step 2: Select Date & Time
  const renderStep2 = () => (
    <div className="max-w-4xl mx-auto relative">
      <LoadingOverlay />
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">選擇有空時段</h2>
          <p className="text-blue-600 font-medium mt-1">已選擇：{selectedCourse?.title} ({selectedCourse?.duration})</p>
        </div>
        <button onClick={() => setStep(1)} className="text-slate-500 hover:text-slate-800 flex items-center gap-1 text-sm bg-white px-3 py-2 rounded-lg border border-slate-200 hover:border-slate-300 transition-colors">
          <ArrowLeft size={16} /> 重選課程
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
          <label className="block text-sm font-medium text-slate-700 mb-2">1. 選擇日期</label>
          <div className="relative">
            <input 
              type="date" 
              className="w-full p-4 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
              min={new Date().toISOString().split('T')[0]}
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
            />
          </div>
          <div className="mt-6 bg-yellow-50 p-4 rounded-lg border border-yellow-100">
            <h4 className="text-sm font-bold text-yellow-800 flex items-center gap-2 mb-2">
              <Clock size={16} /> 系統提示：
            </h4>
            <p className="text-xs text-yellow-700 leading-relaxed">
              丫亮笑長行程繁忙，系統將自動顯示當天剩餘的「有空」時段。灰色代表該時段已被預約。
            </p>
          </div>
        </div>

        <div className="space-y-4 relative">
           <label className="block text-sm font-medium text-slate-700">2. 選擇時段</label>
           
           {!selectedDate ? (
             <div className="h-40 bg-slate-100 rounded-xl border-2 border-dashed border-slate-300 flex items-center justify-center text-slate-400">
               請先選擇左側日期
             </div>
           ) : (
             <>
                <button
                  disabled={!slotAvailability[TimeSlot.MORNING]}
                  onClick={() => handleTimeSelect(TimeSlot.MORNING)}
                  className={`w-full p-6 rounded-xl border-2 transition-all flex flex-col items-center justify-center ${
                    slotAvailability[TimeSlot.MORNING] 
                    ? 'border-blue-200 bg-white hover:border-blue-500 hover:bg-blue-50 cursor-pointer group shadow-sm hover:shadow-md' 
                    : 'border-slate-100 bg-slate-50 cursor-not-allowed opacity-60'
                  }`}
                >
                  <span className={`text-xl font-bold mb-1 ${slotAvailability[TimeSlot.MORNING] ? 'text-slate-800 group-hover:text-blue-700' : 'text-slate-400'}`}>09:00 - 12:00</span>
                  <span className={`text-sm ${slotAvailability[TimeSlot.MORNING] ? 'text-green-600 font-medium bg-green-50 px-2 py-0.5 rounded' : 'text-slate-400'}`}>
                    {slotAvailability[TimeSlot.MORNING] ? '有空 (點選預約)' : '已滿'}
                  </span>
                </button>

                <button
                  disabled={!slotAvailability[TimeSlot.AFTERNOON]}
                  onClick={() => handleTimeSelect(TimeSlot.AFTERNOON)}
                  className={`w-full p-6 rounded-xl border-2 transition-all flex flex-col items-center justify-center ${
                    slotAvailability[TimeSlot.AFTERNOON] 
                    ? 'border-blue-200 bg-white hover:border-blue-500 hover:bg-blue-50 cursor-pointer group shadow-sm hover:shadow-md' 
                    : 'border-slate-100 bg-slate-50 cursor-not-allowed opacity-60'
                  }`}
                >
                  <span className={`text-xl font-bold mb-1 ${slotAvailability[TimeSlot.AFTERNOON] ? 'text-slate-800 group-hover:text-blue-700' : 'text-slate-400'}`}>13:30 - 16:30</span>
                  <span className={`text-sm ${slotAvailability[TimeSlot.AFTERNOON] ? 'text-green-600 font-medium bg-green-50 px-2 py-0.5 rounded' : 'text-slate-400'}`}>
                    {slotAvailability[TimeSlot.AFTERNOON] ? '有空 (點選預約)' : '已滿'}
                  </span>
                </button>
             </>
           )}
        </div>
      </div>
    </div>
  );

  // Step 3: Form
  const renderStep3 = () => (
    <div className="max-w-3xl mx-auto relative">
      <LoadingOverlay />
      <div className="flex items-center justify-between mb-6">
        <div>
           <h2 className="text-2xl font-bold text-slate-800">確認並填寫資料</h2>
           <p className="text-slate-500 mt-1">請完善邀請單位資訊以利後續聯絡</p>
        </div>
        <button onClick={() => setStep(2)} className="text-slate-500 hover:text-slate-800 flex items-center gap-1 text-sm bg-white px-3 py-2 rounded-lg border border-slate-200 hover:border-slate-300 transition-colors">
          <ArrowLeft size={16} /> 重選時段
        </button>
      </div>

      <div className="bg-blue-50 border border-blue-100 rounded-lg p-4 mb-8 flex items-center gap-3 text-blue-800">
        <Calendar size={20} />
        <span className="font-bold text-lg">{selectedDate}</span>
        <span className="w-px h-6 bg-blue-200 mx-2"></span>
        <Clock size={20} />
        <span className="font-bold text-lg">{selectedSlot}</span>
        <span className="w-px h-6 bg-blue-200 mx-2"></span>
        <span className="font-medium">{selectedCourse?.title}</span>
      </div>

      <form onSubmit={handleSubmit} className="bg-white p-8 rounded-xl shadow-sm border border-slate-200 space-y-6">
        {/* 基本資料 */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-700 flex items-center gap-1">
              邀請單位/公司名稱 <span className="text-red-500">*</span>
            </label>
            <input 
              required
              type="text"
              className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all"
              placeholder="例如：台積電文教基金會"
              value={formData.invitingUnit}
              onChange={(e) => setFormData({...formData, invitingUnit: e.target.value})}
            />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-700 flex items-center gap-1">
              聯絡人姓名 <span className="text-red-500">*</span>
            </label>
            <input 
              required
              type="text"
              className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all"
              placeholder="王小明"
              value={formData.contactName}
              onChange={(e) => setFormData({...formData, contactName: e.target.value})}
            />
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-700 flex items-center gap-1">
              聯絡電話 <span className="text-red-500">*</span>
            </label>
            <input 
              required
              type="tel"
              className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all"
              placeholder="0912-345-678"
              value={formData.contactPhone}
              onChange={(e) => setFormData({...formData, contactPhone: e.target.value})}
            />
          </div>
          <div className="space-y-2">
             <label className="text-sm font-semibold text-slate-700 flex items-center gap-1">
              聯絡人Email
            </label>
            <div className="relative">
              <Mail size={18} className="absolute left-3 top-3.5 text-slate-400" />
              <input 
                type="email"
                className="w-full p-3 pl-10 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                placeholder="example@email.com"
                value={formData.contactEmail}
                onChange={(e) => setFormData({...formData, contactEmail: e.target.value})}
              />
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
           <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-700 flex items-center gap-1">
              聯絡人社群帳號 (Line/FB擇一) <span className="text-red-500">*</span>
            </label>
            <div className="relative">
               <MessageSquare size={18} className="absolute left-3 top-3.5 text-slate-400" />
               <input 
                required
                type="text"
                className="w-full p-3 pl-10 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                placeholder="Line ID 或 FB 連結"
                value={formData.contactSocial}
                onChange={(e) => setFormData({...formData, contactSocial: e.target.value})}
              />
            </div>
          </div>
          <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-700 flex items-center gap-1">
              邀請縣市 <span className="text-red-500">*</span>
            </label>
            <div className="relative">
              <MapPin size={18} className="absolute left-3 top-3.5 text-slate-400" />
              <select 
                required
                className="w-full p-3 pl-10 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none bg-white"
                value={formData.city}
                onChange={(e) => setFormData({...formData, city: e.target.value})}
              >
                <option value="">請選擇</option>
                {CITIES.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>
          </div>
        </div>

        {/* 費用相關 */}
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200 grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-700 flex items-center gap-1">
              預計鐘點費/hr (新台幣)
            </label>
            <div className="relative">
               <DollarSign size={18} className="absolute left-3 top-3.5 text-slate-400" />
               <input 
                type="number"
                min="0"
                className="w-full p-3 pl-10 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                placeholder="例如: 2000"
                value={formData.hourlyRate}
                onChange={(e) => setFormData({...formData, hourlyRate: e.target.value})}
              />
            </div>
          </div>
          <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-700 flex items-center gap-1">
              <Car size={16} /> 車馬費提供
            </label>
            <div className="flex gap-4 mt-3">
               <label className="flex items-center gap-2 cursor-pointer">
                 <input 
                    type="radio" 
                    name="travelFee" 
                    value="yes"
                    checked={formData.hasTravelFee === 'yes'}
                    onChange={() => setFormData({...formData, hasTravelFee: 'yes'})}
                    className="w-5 h-5 text-blue-600"
                 />
                 <span className="text-slate-700">有提供實報實銷或定額</span>
               </label>
               <label className="flex items-center gap-2 cursor-pointer">
                 <input 
                    type="radio" 
                    name="travelFee" 
                    value="no"
                    checked={formData.hasTravelFee === 'no'}
                    onChange={() => setFormData({...formData, hasTravelFee: 'no'})}
                    className="w-5 h-5 text-blue-600"
                 />
                 <span className="text-slate-700">無</span>
               </label>
            </div>
          </div>
        </div>

        <div className="space-y-2">
          <label className="text-sm font-semibold text-slate-700">備註需求</label>
          <textarea 
            className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all h-32"
            placeholder="例如：需自備投影筆、停車位安排..."
            value={formData.notes}
            onChange={(e) => setFormData({...formData, notes: e.target.value})}
          />
        </div>

        <div className="pt-4">
          <button 
            type="submit"
            disabled={loading}
            className={`w-full text-white font-bold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 ${loading ? 'bg-slate-400 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-700'}`}
          >
            {loading ? '處理中...' : '確認並送出預約'}
          </button>
        </div>
      </form>
    </div>
  );

  const renderStep4 = () => (
    <div className="max-w-2xl mx-auto text-center py-12">
      <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6 animate-bounce">
        <Check size={40} className="text-green-600" />
      </div>
      <h2 className="text-3xl font-bold text-slate-800 mb-4">預約申請已送出！</h2>
      <p className="text-slate-600 text-lg mb-8 leading-relaxed">
        感謝您的填寫。我們已收到您的預約申請：<br/>
        <span className="font-bold text-slate-800">{selectedCourse?.title}</span> - 
        <span className="font-bold text-slate-800"> {selectedDate} ({selectedSlot})</span>
      </p>
      
      <div className="bg-yellow-50 border border-yellow-100 rounded-xl p-6 text-left mb-8 max-w-lg mx-auto">
        <h4 className="font-bold text-yellow-800 mb-2 flex items-center gap-2">
           <Clock size={18} /> 後續流程說明：
        </h4>
        <ul className="list-disc list-inside text-yellow-700 space-y-2 text-sm">
           <li>此階段僅為「預約申請」，尚未確認成立。</li>
           <li>我們將於 3 個工作天內透過電話或 Email 與您聯繫。</li>
           <li>確認合作細節與費用後，將發送正式確認信。</li>
        </ul>
      </div>

      <button 
        onClick={handleReset}
        className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-8 rounded-xl transition-all shadow-lg hover:shadow-xl"
      >
        回到首頁
      </button>
    </div>
  );

  return (
    <div className="pt-4 pb-12">
      {step === 1 && <WelcomeBox />}
      <StepIndicator />
      {step === 1 && renderStep1()}
      {step === 2 && renderStep2()}
      {step === 3 && renderStep3()}
      {step === 4 && renderStep4()}
    </div>
  );
};